---
defaults: &defaults
  docker:
    - image: cimg/node:lts
  environment:
  working_directory: ~/project

version: 2
jobs:
  run-tests:
    <<: *defaults
    steps:
      - checkout
      - run: yarn
      - run:
          name: Run tests
          command: yarn test
          paths:
            - node_modules
  check-prettier:
    <<: *defaults
    steps:
      - checkout
      - run: yarn
      - run:
          name: Run tests
          command: yarn prettier --check 'src/**/*'
          paths:
            - node_modules
  check-eslint:
    <<: *defaults
    steps:
      - checkout
      - run: yarn
      - run:
          name: Run linter
          command: yarn run eslint-check
          paths:
            - node_modules
  check-stylelint:
    <<: *defaults
    steps:
      - checkout
      - run: yarn
      - run:
          name: Run linter
          command: yarn run stylelint-check
          paths:
            - node_modules
  check-types:
    <<: *defaults
    steps:
      - checkout
      - run: yarn
      - run:
          name: Run Typescript build
          command: yarn run typescript-build
          paths:
            - node_modules
workflows:
  version: 2
  build:
    jobs:
      - run-tests
      - check-prettier
      - check-eslint
      - check-stylelint
      - check-types
