---
defaults: &defaults
  docker:
    - image: canonicalwebteam/dev
  environment:
  working_directory: ~/project

version: 2
jobs:
  run-tests:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Run tests
          command: yarn test
workflows:
  version: 2
  build:
    jobs:
      - run-tests
